# Generated by Django 4.2 on 2025-11-15 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meet.utils
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meet",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=meet.utils.generate_meet_id,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "channel_name",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_meets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="meets", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
