# Generated by Django 4.2 on 2025-11-08 16:50

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="groupinvite",
            name="code",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=50, unique=True
            ),
        ),
    ]
