# Generated by Django 4.2 on 2025-11-17 13:09

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_alter_chatroom_id_alter_chatroom_room_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                max_length=30,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("direct", "Direct Message"),
                    ("group", "Group Chat"),
                    ("video_call", "Video Call"),
                ],
                default="direct",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="groupinvite",
            name="code",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=50, unique=True
            ),
        ),
    ]
