# Generated by Django 4.2 on 2025-11-19 13:28

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_alter_chatroom_id_alter_groupinvite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="id",
            field=models.CharField(
                default=chat.models.generate_short_uuid,
                max_length=30,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="groupinvite",
            name="code",
            field=models.CharField(
                default=chat.models.generate_short_uuid, max_length=50, unique=True
            ),
        ),
    ]
