# Generated by Django 4.2 on 2025-11-10 14:08

from django.db import migrations, models
import utils.file_uploads


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialty",
            options={
                "ordering": ["name"],
                "verbose_name": "Specialty",
                "verbose_name_plural": "Specialties",
            },
        ),
        migrations.AddField(
            model_name="specialty",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="specialty",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=utils.file_uploads.upload_specialty_img
            ),
        ),
    ]
