# Generated by Django 4.2 on 2025-10-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0002_adminprofile_created_at_adminprofile_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="city",
            field=models.CharField(
                blank=True, help_text="City or Town", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="country",
            field=models.CharField(blank=True, help_text="Country", max_length=100),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="state",
            field=models.CharField(
                blank=True, help_text="State or Province", max_length=100
            ),
        ),
    ]
