# Generated by Django 4.2 on 2025-09-04 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.file_uploads
import utils.validations
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "dob",
                    models.DateField(blank=True, help_text="Date of Birth", null=True),
                ),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("website", models.URLField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.file_uploads.upload_profile_photo,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "country",
                    models.CharField(blank=True, help_text="Country", max_length=100),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="State or Province", max_length=100
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City or Town", max_length=100
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "id_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=utils.file_uploads.upload_id_documents,
                        validators=[utils.validations.validate_id_file],
                    ),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("SUSPENDED", "SUSPENDED"),
                        ],
                        default="PENDING",
                        help_text="KYC status of the user",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "MALE"),
                            ("FEMALE", "FEMALE"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientKYCRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("SUSPENDED", "SUSPENDED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_records",
                        to="patients.patient",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_kyc_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient KYC Record",
                "verbose_name_plural": "Patient KYC Records",
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientEmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("relationship", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                        ],
                        default="phone",
                        max_length=10,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Emergency Contact",
                "verbose_name_plural": "Patient Emergency Contacts",
                "ordering": ["name"],
            },
        ),
    ]
