# Generated by Django 4.2 on 2025-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("VERIFIED", "VERIFIED"),
                    ("REJECTED", "REJECTED"),
                    ("SUSPENDED", "SUSPENDED"),
                ],
                default="PENDING",
                help_text="KYC status of the user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="patientkycrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("VERIFIED", "VERIFIED"),
                    ("REJECTED", "REJECTED"),
                    ("SUSPENDED", "SUSPENDED"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
