# Generated by Django 4.2 on 2025-11-03 16:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0004_alter_patient_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0004_alter_doctor_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("follow_up", "Follow-up"),
                            ("urgent_care", "Urgent Care"),
                            ("mental_health", "Mental Health Session"),
                            ("general_checkup", "General Checkup"),
                            ("specialist", "Specialist Consultation"),
                        ],
                        default="consultation",
                        max_length=50,
                        verbose_name="Appointment Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "scheduled_start_time",
                    models.DateTimeField(
                        db_index=True, verbose_name="Scheduled Start Time"
                    ),
                ),
                (
                    "scheduled_end_time",
                    models.DateTimeField(verbose_name="Scheduled End Time"),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone for the appointment",
                        max_length=50,
                        verbose_name="Timezone",
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True,
                        help_text="Video conference URL or room identifier",
                        max_length=500,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Meeting Link/Room ID",
                    ),
                ),
                (
                    "technical_issues_reported",
                    models.TextField(
                        blank=True,
                        help_text="Any technical issues during the appointment",
                        null=True,
                        verbose_name="Technical Issues Reported",
                    ),
                ),
                (
                    "reason_for_visit",
                    models.TextField(
                        help_text="Chief complaint or purpose of the appointment",
                        verbose_name="Reason for Visit",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Special instructions for patient or provider",
                        null=True,
                        verbose_name="Notes/Instructions",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Cancellation Reason"
                    ),
                ),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("patient", "Patient"),
                            ("doctor", "Doctor"),
                            ("system", "System"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Cancelled By",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="doctors.doctor",
                        verbose_name="Doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["-scheduled_start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["scheduled_start_time", "status"],
                name="appointment_schedul_368cae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "scheduled_start_time"],
                name="appointment_patient_20e185_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "scheduled_start_time"],
                name="appointment_doctor__c60a98_idx",
            ),
        ),
    ]
