# Generated by Django 4.2 on 2025-11-03 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="reason_for_visit",
            new_name="reason",
        ),
    ]
