# Generated by Django 4.2 on 2025-11-15 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meet", "0001_initial"),
        ("appointments", "0002_rename_reason_for_visit_appointment_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="meeting_link",
        ),
        migrations.AddField(
            model_name="appointment",
            name="meet",
            field=models.OneToOneField(
                blank=True,
                help_text="Associated video meeting room",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment",
                to="meet.meet",
                verbose_name="Video Meeting",
            ),
        ),
    ]
