# Generated by Django 4.2 on 2025-11-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0004_alter_appointment_appointment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("consultation", "Consultation"),
                    ("follow_up", "Follow Up"),
                    ("urgent_care", "Urgent Care"),
                    ("mental_health", "Mental Health Session"),
                    ("general_checkup", "General Checkup"),
                ],
                default="consultation",
                max_length=50,
                verbose_name="Appointment Type",
            ),
        ),
    ]
