# Generated by Django 4.2 on 2025-09-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospitals", "0002_alter_hospital_kyc_status_and_more"),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctors",
                to="hospitals.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("VERIFIED", "VERIFIED"),
                    ("REJECTED", "REJECTED"),
                    ("SUSPENDED", "SUSPENDED"),
                ],
                default="PENDING",
                help_text="KYC status of the user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="doctorkycrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("VERIFIED", "VERIFIED"),
                    ("REJECTED", "REJECTED"),
                    ("SUSPENDED", "SUSPENDED"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
