# Generated by Django 4.2 on 2025-11-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0004_alter_doctor_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_pending_approval",
            field=models.BooleanField(default=False),
        ),
    ]
