# Generated by Django 4.2 on 2025-11-24 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("version", models.CharField(default="v1.0", max_length=50)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("imaging", "Imaging"),
                            ("json", "JSON"),
                            ("signal", "Signal"),
                        ],
                        default="imaging",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("stable", "Stable"),
                            ("beta", "Beta"),
                            ("research", "Research"),
                        ],
                        default="research",
                        max_length=20,
                    ),
                ),
                ("icon_name", models.CharField(default="Activity", max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="model_images/"),
                ),
                ("model_url", models.URLField(blank=True, null=True)),
                ("docs_url", models.URLField(blank=True, null=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="model_docs/"),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tags", models.ManyToManyField(blank=True, to="ai_models.tag")),
            ],
            options={
                "verbose_name": "AI Model",
                "verbose_name_plural": "AI Models",
                "ordering": ["-created_at"],
            },
        ),
    ]
