# Generated by Django 4.2 on 2025-09-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospitals", "0002_alter_hospital_kyc_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
