# Generated by Django 4.2 on 2025-10-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospitals", "0003_hospital_is_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
