# Generated by Django 4.2 on 2025-11-10 13:28

from django.db import migrations, models
import utils.file_uploads


class Migration(migrations.Migration):
    dependencies = [
        ("hospitals", "0004_alter_hospital_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=utils.file_uploads.upload_cover_image
            ),
        ),
    ]
