# Generated by Django 4.2 on 2025-11-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
        ("hospitals", "0005_hospital_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="specialties",
            field=models.ManyToManyField(
                blank=True, related_name="hospitals", to="profiles.specialty"
            ),
        ),
    ]
