# Generated by Django 4.2 on 2025-11-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospitals", "0006_hospital_specialties"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="is_pending_approval",
            field=models.BooleanField(default=False),
        ),
    ]
